services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: saas-starter-kit
    ports:
      - 5432:5432
